### ISSUE TITLE
column "Message" does not exist while using postgresql as db provider

### ISSUE THREAD

**Issue by amirelkassar** [serilog-contrib/serilog-ui#157]
**Describe the bug**
I'm receiving an Npgsql.PostgresException with error code 42703, indicating that the column "Message" does not exist in the PostgreSQL database. This error occurs when trying to fetch logs using Serilog.Ui.PostgreSqlProvider. The error suggests that the query might be referencing "Message" instead of "message" or another case-sensitive variant.

**To Reproduce**
1. Set up Serilog with Serilog.Ui.PostgreSqlProvider in a PostgreSQL database where logs are stored.
3. Observe the error message about the missing "Message" column.

**Expected behavior**
The logs should be retrieved successfully without a case-sensitive column mismatch.

**Error Message**
`Npgsql.PostgresException (0x80004005): 42703: column "Message" does not exist
  Position: 8
  at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
  at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
  at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
  ...
  Exception data:
    Severity: ERROR
    SqlState: 42703
    MessageText: column "Message" does not exist
    Hint: Perhaps you meant to reference the column "logs.message".
    Position: 8
    File: parse_relation.c
    Line: 3738
    Routine: errorMissingColumn`

**Additional context**

**Comment by mo-esmp** [comment]
Could you specify the PostgreSQL sink you are using? [PostgreSQL](https://github.com/b00ted/serilog-sinks-postgresql) or [PostgreSQLalternative](https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative)?

**Comment by lonix1** [comment]
Same problem here. I'm using the "alternative" provider.

Note that in my case the "Message" column really is missing. I don't include it as I rely on the "MessageTemplate" instead (inside the json column).

I see that the column names are defined [here](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.PostgreSqlProvider/Models/PostgreSqlAlternativeSinkColumnNames.cs). I don't use those. Am I still able to use this package?

---
UPDATE

I found [some instructions](https://github.com/serilog-contrib/serilog-ui/wiki/Providers-Info#steps-to-configure-additional-columns) for customisation, so I did this:
```cs
public class CustomPostgresLogModel : PostgresLogModel {
  [RemovedColumn] public override string? Exception { get; set; }
  // cannot do this as they are sealed:
  //[RemovedColumn] public override string? Message { get; set; }
  //[RemovedColumn] public override DateTime Timestamp { get; set; }
}
```

**Comment by followynne** [comment]
> Same problem here. I'm using the "alternative" provider.
> 
> Note that in my case the "Message" column really is missing. I don't include it as I rely on the "MessageTemplate" instead (inside the json column).
> 
> I see that the column names are defined [here](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.PostgreSqlProvider/Models/PostgreSqlAlternativeSinkColumnNames.cs). I don't use those. Am I still able to use this package?
> 
> UPDATE
> 
> I found [some instructions](https://github.com/serilog-contrib/serilog-ui/wiki/Providers-Info#steps-to-configure-additional-columns) for customisation, so I did this:
> 
> ```cs
> public class CustomPostgresLogModel : PostgresLogModel {
>   [RemovedColumn] public override string? Exception { get; set; }
>   // cannot do this as they are sealed:
>   //[RemovedColumn] public override string? Message { get; set; }
>   //[RemovedColumn] public override DateTime Timestamp { get; set; }
> }
> ```

hello @lonix1 

as a design choice, Message column is not removable as it's required for the UI current page (as you'll see from screenshots sample, it's part of the required columns).

**Comment by lonix1** [comment]
Yes I realised that once I started tinkering with this library, some columns are required. I think that will please many users, but not everyone as is always the case.

It would be nice in the future if it were possible to customise the UI's columns, but I'm sure that would be a lot of work. Thanks for the reply.

**Comment by esavkin** [comment]
I think the issue is that the column names in the table start with a lowercase letter. Try switching to SerilogSinksPostgreSQL
f.e.:
```
            services.AddSerilogUi(options => options
                .UseNpgSql(opts => opts
                .WithSinkType(Serilog.Ui.PostgreSqlProvider.Models.PostgreSqlSinkType.SerilogSinksPostgreSQL) ...
```

**Comment by amirelkassar** [comment]
@esavkin thanks for the answer .
I've tried to change the sink type as u mentioned, however it says that the SerilogSinksPostgreSQL is obsolete it works for me
