### ISSUE TITLE
Could not load file or assembly 'Serilog.Ui.Core, Version=2.1.0'

### ISSUE THREAD

**Issue by sommmen** [serilog-contrib/serilog-ui#79]
**Describe the bug**
In production, i have 2 webapps and one background processor, both using nearly the same serilog configuration.
Recently some package upgrades came to my attention;

![image](https://github.com/serilog-contrib/serilog-ui/assets/8641495/19227029-c45a-49e6-81da-e56d3afeba26)

This build works locally, but for some reason not on my production server;

``` csharp
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Serilog.Ui.Core, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Serilog.Ui.Core, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Serilog.Settings.Configuration.ConfigurationReader.LoadConfigurationAssemblies(IConfiguration section, AssemblyFinder assemblyFinder)
   at Serilog.Settings.Configuration.ConfigurationReader..ctor(IConfiguration configSection, AssemblyFinder assemblyFinder, ConfigurationReaderOptions readerOptions, IConfiguration configuration)
   at Serilog.ConfigurationLoggerConfigurationExtensions.GetConfigurationReader(IConfiguration configuration, ConfigurationReaderOptions readerOptions, DependencyContext dependencyContext)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, ConfigurationReaderOptions readerOptions)
```

- Both web apps run under IIS and they both are not able to startup. The background processor seems to run fine - but it's hard to see.

I'm unsure why this happens and i'm curious if this impacts others, or any suggestions on what may cause this.

**To Reproduce**

Have not found a way to reproduce (yet) - but i'll hope to gather more information after some time.

**Expected behavior**
The app to startup normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser n/a
 - Version 2.4.0 (latest)

**Comment by mo-esmp** [comment]
The latest version is `2.4.0`, please upgrade to the latest version.

**Comment by sommmen** [comment]
> The latest version is `2.4.0`, please upgrade to the latest version.

Apologies this was the serilog version. 
I'm thinking this has something to do with the `serilog.settings.configuration` package, not so much with this library.
